/**
 * Session context for coding follow-up questions.
 *
 * ── The problem this solves ─────────────────────────────────────────────────
 * An interviewer sets a problem ("Given an array of integers, find the two
 * numbers that sum to a target"). The candidate works on it. Then the
 * interviewer asks "Why did you use a HashSet?" or "Can you optimize it?"
 *
 * Ghostly answered only the latest question. Two independent reasons, and only
 * fixing one of them would still leave the bug:
 *
 *   1. The problem statement is not in the prompt. `buildInterviewUserPrompt`
 *      only carries `turn.finals` — and the visible chat is routinely cleared
 *      between the problem and the follow-up, so by then `finals` holds only
 *      the follow-up itself.
 *   2. Even if it were carried, it would be labelled as BACKGROUND with "do NOT
 *      answer anything in here", which is precisely the wrong instruction for
 *      the thing a follow-up question is *about*.
 *
 * ── Design rules, and why each one exists ───────────────────────────────────
 *
 *   NO EXTRA LLM CALL. Everything here is a regex and a truncation. A summary
 *   generated by a model would cost latency on every turn and could fail, and a
 *   failed summary must never be able to block an answer.
 *
 *   NO TOPIC WHITELIST. The cues below are structural vocabulary — deictic
 *   references and follow-up phrasings — that carries no domain meaning. A topic
 *   list would fail the first unseen problem and would be the reason this
 *   feature cannot be trusted.
 *
 *   ATTACH IS ADVISORY, NOT AUTHORITATIVE. The block says "use this only if the
 *   latest question refers to it". A false positive therefore costs a little
 *   prompt, never a wrong answer, because the system prompt's absolute rules
 *   still say "answer exactly one thing: the text between
 *   <<<LATEST_QUESTION>>> and <<<END_LATEST_QUESTION>>>".
 *
 *   IN-MEMORY ONLY. Never persisted. An interview context that survives a
 *   restart could be wrong about what is being discussed, which is worse than
 *   having no context.
 */

import type { ConversationThread } from "./conversationThread";

/** What kind of problem is active. Affects labelling only, never the decision. */
export type ProblemKind = "coding" | "system_design" | "other";

/** Where the problem statement came from. Never auto-set from the AI's output. */
export type ProblemSource = "spoken" | "screenshot" | "manual";

export interface ActiveProblem {
  id: string;
  /** The corrected question, as the pipeline would use it. */
  text: string;
  kind: ProblemKind;
  source: ProblemSource;
  createdAt: number;
  /** Refreshed every time the context is attached, so TTL is "since last use". */
  lastUsedAt: number;
}

export interface SessionContext {
  activeProblem: ActiveProblem | null;
  /**
   * The drill-down layer: a technical / project discussion, carried across
   * questions.
   *
   * Kept INSIDE this object rather than in a parallel slice on purpose. The two
   * layers are related but not interchangeable, and "one context system, not two
   * independent ones" is only true if they are stored, cleared and reasoned
   * about together. See `conversationThread.ts` for the layer itself.
   *
   * Cleared by Reset Interview, NOT by Clear Chat or Next Question.
   */
  conversationThread: ConversationThread | null;
  /**
   * A short deterministic excerpt of a VALIDATED answer.
   *
   * Phrased as what GHOSTLY suggested, never as what the candidate did. This is
   * not pedantry: the model has no way to tell the difference between the two,
   * and an answer that said "you used a hash map" would be a fabrication.
   */
  approachSummary: string | null;
  /** Optional pasted problem statement or code, typed by the user. */
  userNotes: string | null;
}

export const EMPTY_SESSION_CONTEXT: SessionContext = {
  activeProblem: null,
  conversationThread: null,
  approachSummary: null,
  userNotes: null,
};

// ── Caps and TTL ────────────────────────────────────────────────────────────

/** Hard cap on the stored problem statement. */
export const PROBLEM_TEXT_MAX_CHARS = 600;

/** Hard cap on the deterministic approach excerpt. */
export const APPROACH_SUMMARY_MAX_CHARS = 200;

/** Hard cap on pasted user notes (a problem statement or a code sketch). */
export const USER_NOTES_MAX_CHARS = 800;

/**
 * How long a problem stays active after it was last USED, in ms.
 *
 * "Since last use", not "since created": a follow-up five minutes later is the
 * normal case, and a TTL from creation would expire the context in the middle of
 * exactly the exchange it exists for.
 *
 * 30 minutes is longer than a typical gap between a problem and its follow-ups
 * and shorter than a coffee break, so a resumed conversation does not inherit a
 * problem from an hour ago.
 */
export const SESSION_CONTEXT_TTL_MS = 30 * 60 * 1000;

// ── Problem detection ───────────────────────────────────────────────────────

/**
 * Structural cues that a question introduces a NEW problem to work on.
 *
 * Every alternative is an imperative request with a DEFINITE object: "write a
 * function", "implement a cache", "find the shortest path", "given an array…".
 *
 * ── Why `it` / `this` / `that` are deliberately excluded ─────────────────────
 * "Can you implement it?" and "Now write this" are follow-ups, not new
 * problems, and admitting them would REPLACE the active problem with a question
 * that does not contain one — destroying the context on the second turn of the
 * most common exchange there is. A new problem states its object; a follow-up
 * refers to it.
 */
const NEW_PROBLEM_CUES: RegExp[] = [
  // "write a function", "code a class", "implement a method"
  /\b(?:write|code|implement|build|create|solve|refactor|rewrite|fix|optimi[sz]e)\s+(?:a|an|the|your|me)\b/i,
  // "how would you design / architect / structure / approach this"
  /\bhow\s+(?:would|will|do|should)\s+you\s+(?:design|architect|structure|lay out|solve|approach|implement|build)\b/i,
  // "design a rate limiter", "design an API"
  /\b(?:design|architect)\s+(?:a|an|the|your)\b/i,
  // "given an array of integers, …" / "given a linked list"
  /\bgiven\s+(?:an?|the|you|these|two|three)\b/i,
  // "find the shortest path", "find all duplicates"
  /\b(?:find|return|compute|count|reverse|sort|merge|invert|rotate|detect|remove|group)\s+(?:the|all|a|an|every|each)\b/i,
  // "walk me through implementing / solving"
  /\bwalk\s+(?:me|us)\s+through\s+(?:how|implementing|solving|designing|building)\b/i,
];

/**
 * Questions that ask ABOUT something rather than posing work to do.
 *
 * These must not replace the active problem, and — critically — must not CLEAR
 * it either. "Explain Docker" in the middle of a working session is a detour,
 * not an abandonment: clearing here is what would make the context useless the
 * moment an interviewer glances sideways.
 *
 * Ordered before {@link NEW_PROBLEM_CUES} is NOT how it is applied (see
 * {@link detectProblemStart}); it is applied as an explicit veto, so a phrase
 * like "explain how you would design a cache" still counts as a new problem.
 */
const DEFINITION_CUES = new RegExp(
  [
    // "what is X", "what are X", "what does X do"
    "^\\s*what\\s+(?:is|are|was|were|does|do|did)\\b",
    // "explain X", "tell me about X", "describe X"
    "^\\s*(?:explain|tell me about|describe|define|walk me through what)\\b",
    // "why does X happen", "how does X work"
    "^\\s*(?:how|why)\\s+does\\b",
    "^\\s*why\\s+(?:is|are|was|were)\\b",
    // "what do you know about X"
    "^\\s*what\\s+do\\s+you\\s+(?:know|think)\\b",
  ].join("|"),
  "i",
);

/**
 * The second half of {@link DEFINITION_CUES}' veto: the question looks like a
 * definition but actually asks for work.
 *
 * Without this, "Explain how you would design a rate limiter" would be vetoed
 * as a definition, which is the opposite of what it is.
 */
const ASKS_FOR_WORK = /\b(?:design|implement|write|code|build|solve|create|refactor|compute|find)\b/i;

export function detectProblemStart(
  question: string,
): { isProblemStart: boolean; kind: ProblemKind; reason: string } {
  const text = (question ?? "").trim();
  if (text.length < 4) {
    return {
      isProblemStart: false,
      kind: "other",
      reason: "too short to classify",
    };
  }

  const looksLikeWork = NEW_PROBLEM_CUES.some((re) => re.test(text));
  const looksLikeDefinition = DEFINITION_CUES.test(text) && !ASKS_FOR_WORK.test(text);

  // Definition wins over a weak cue, but never over an explicit request for work.
  if (looksLikeDefinition) {
    return {
      isProblemStart: false,
      kind: "other",
      reason: "a definition or conceptual question does not start a problem",
    };
  }
  if (!looksLikeWork) {
    return {
      isProblemStart: false,
      kind: "other",
      reason: "no structural cue for a new problem",
    };
  }

  return {
    isProblemStart: true,
    kind: classifyProblemKind(text),
    reason: "matched a problem-start cue",
  };
}

/** `system_design` only when the question is plainly about a system shape. */
function classifyProblemKind(text: string): ProblemKind {
  if (
    /\b(?:design|architect|system|architecture|scale|scalab|throughput|service|microservice|infrastructure|distributed|api)\b/i.test(
      text,
    )
  ) {
    return "system_design";
  }
  if (/\b(?:function|array|string|algorithm|code|implement|loop|recursion|data structure|integer)\b/i.test(text)) {
    return "coding";
  }
  return "other";
}

// ── Follow-up classification ────────────────────────────────────────────────

/**
 * Structural follow-up cues. Grouped so the reason can say WHICH one matched —
 * a wrong reason in the log is how the next debugging session starts.
 *
 * ── Why these are safe ───────────────────────────────────────────────────────
 * None of them names a technology, a data structure, or a language. They are the
 * grammar of referring back to something already said. "Why did you use a
 * HashSet here?" and "Why did you use the event loop here?" match for exactly
 * the same reason, and neither match is because of a topic.
 */
const FOLLOW_UP_CUE_GROUPS: Array<{ reason: string; re: RegExp }> = [
  {
    reason: "refers to the earlier work (your solution / approach / this / it)",
    re: /\b(?:your|the)\s+(?:solution|approach|code|answer|implementation|design|algorithm|solution)\b|\b(?:this|that|it|here)\b/i,
  },
  {
    reason: "asks why a past choice was made",
    re: /\bwhy\s+(?:did|do|does|was|were|have|has)\s+(?:you|we|that|this|it|the)\b|\bwhy\s+not\b|\bwhy\s+(?:isn'?t|wasn'?t|didn'?t|doesn'?t|can'?t|couldn'?t)\b/i,
  },
  {
    reason: "asks about a hypothetical variation",
    re: /\bwhat\s+if\b|\bwhat\s+happens?\s+(?:when|if)\b|\bwhat\s+would\s+happen\b/i,
  },
  {
    reason: "asks about complexity",
    // `complexity` alone rather than "time complexity": ASR routinely drops a
    // word, and the cue has to survive "whats the complexity of that".
    re: /\b(?:time|space|computational)\s+complexity\b|\bcomplexity\b/i,
  },
  {
    reason: "asks to improve the existing work",
    re: /\b(?:optimi[sz]e|improv(?:e|ement)|speed\s*up|faster|make\s+it\s+(?:faster|better|simpler))\b/i,
  },
  {
    reason: "asks about robustness",
    re: /\bedge\s+cases?\b|\bfail(?:ure|s|ing)?\b.*\b(?:when|if)\b|\bwhat\s+if\b/i,
  },
];

/** Why a context was or was not attached. Stable strings — they go in the log. */
export type FollowUpReason =
  | "attached"
  | "no active problem"
  | "context expired (older than the TTL)"
  | "not a follow-up: no structural cue"
  | "not a follow-up: a new problem replaces it";

export interface FollowUpVerdict {
  attach: boolean;
  reason: FollowUpReason;
  /** Which cue matched. Only set when `attach` is true. */
  cue?: string;
}

/**
 * Should this question be answered WITH the active problem?
 *
 * ── Precedence, and why ──────────────────────────────────────────────────────
 *  1. No active problem → no.
 *  2. A NEW problem start → no, and the caller REPLACES the context. This runs
 *     before the cue scan so "Now write a hash map" cannot be answered using the
 *     problem it just replaced.
 *  3. Expired by TTL → no. An hour-old problem is a different conversation.
 *  4. Otherwise, any structural cue → yes.
 *
 * The cue scan is an OR over four independent groups, so a question only needs
 * one of them. Requiring more would be more precise but would silently lose the
 * common cases, which is the failure this feature exists to prevent.
 */
export function classifyFollowUp(
  question: string,
  ctx: SessionContext,
  now: number,
): FollowUpVerdict {
  if (!ctx.activeProblem) {
    return { attach: false, reason: "no active problem" };
  }

  if (detectProblemStart(question).isProblemStart) {
    return { attach: false, reason: "not a follow-up: a new problem replaces it" };
  }

  if (now - ctx.activeProblem.lastUsedAt > SESSION_CONTEXT_TTL_MS) {
    return { attach: false, reason: "context expired (older than the TTL)" };
  }

  const text = (question ?? "").trim();
  for (const group of FOLLOW_UP_CUE_GROUPS) {
    if (group.re.test(text)) {
      return { attach: true, reason: "attached", cue: group.reason };
    }
  }

  return { attach: false, reason: "not a follow-up: no structural cue" };
}

// ── Context construction ────────────────────────────────────────────────────

let idCounter = 0;

/** Monotonic in-process id. Never persisted, so a counter is sufficient. */
function nextProblemId(): string {
  idCounter += 1;
  return `p${idCounter}`;
}

/** Trim on a word boundary, with an ellipsis only when something was removed. */
function clip(text: string, max: number): string {
  const t = text.trim();
  if (t.length <= max) return t;
  const cut = t.slice(0, max);
  const lastSpace = cut.lastIndexOf(" ");
  const body = lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut;
  return `${body.trimEnd()}…`;
}

export function clipProblemText(text: string): string {
  return clip(text, PROBLEM_TEXT_MAX_CHARS);
}

export function clipUserNotes(text: string): string {
  return clip(text, USER_NOTES_MAX_CHARS);
}

/**
 * Build the deterministic approach excerpt from a VALIDATED answer.
 *
 * ── Deterministic, by requirement ───────────────────────────────────────────
 * No model call, so no latency, no quota, and no failure mode that could block
 * an answer. It is the first {@link APPROACH_SUMMARY_MAX_CHARS} characters of the
 * answer at a word boundary.
 *
 * ── Why the caller must only pass a validated answer ─────────────────────────
 * An answer that failed the output gate is, by definition, a prompt artefact or
 * a refusal. Summarising one would put garbage into every later prompt, and the
 * garbage would be there specifically because it looked unusual enough to be
 * worth attaching.
 *
 * ── Framing ─────────────────────────────────────────────────────────────────
 * The excerpt is stored WITHOUT a subject, and the subject is supplied by the
 * prompt block as "Ghostly's earlier suggested approach". Storing "you used a
 * hash map" here would be indistinguishable from a real observation to the model
 * on the next turn.
 */
export function extractApproachSummary(answer: string): string | null {
  const text = (answer ?? "").trim();
  if (text.length < 20) return null;
  return clip(text, APPROACH_SUMMARY_MAX_CHARS);
}

/** Build the prompt block. Returns `""` when there is nothing worth sending. */
export function buildContextBlock(ctx: SessionContext): string {
  const lines: string[] = [];
  if (ctx.activeProblem) {
    lines.push(
      `Active problem: ${clipProblemText(ctx.activeProblem.text)}`,
    );
  }
  if (ctx.approachSummary?.trim()) {
    lines.push(
      `Ghostly's earlier suggested approach: ${clip(
        ctx.approachSummary,
        APPROACH_SUMMARY_MAX_CHARS,
      )}`,
    );
  }
  if (ctx.userNotes?.trim()) {
    lines.push(`User notes: ${clipUserNotes(ctx.userNotes)}`);
  }
  if (lines.length === 0) return "";
  return lines.join("\n");
}

/** One-line description for the context chip and the log. */
export function describeSessionContext(ctx: SessionContext, now: number): string {
  if (!ctx.activeProblem) return "no active problem";
  const ageMin = Math.round((now - ctx.activeProblem.createdAt) / 60_000);
  const expired = now - ctx.activeProblem.lastUsedAt > SESSION_CONTEXT_TTL_MS;
  return `${ctx.activeProblem.kind} · set ${ageMin}m ago · ${
    expired ? "expired" : "active"
  }`;
}

/** Apply a TTL check and clear an expired problem. Returns the same object when nothing changed. */
export function pruneSessionContext(
  ctx: SessionContext,
  now: number,
): SessionContext {
  if (
    ctx.activeProblem &&
    now - ctx.activeProblem.lastUsedAt > SESSION_CONTEXT_TTL_MS
  ) {
    // The approach summary and user notes are tied to the problem; keeping them
    // would leave a half-context that attaches to nothing. The THREAD is pruned
    // on its own clock (`THREAD_TTL_MS`) by the caller via `continueThread`,
    // because its lifecycle is deliberately shorter.
    return {
      ...ctx,
      activeProblem: null,
      approachSummary: null,
      userNotes: null,
    };
  }
  return ctx;
}

/** Create or replace the active problem from a spoken question. */
export function startProblem(
  ctx: SessionContext,
  question: string,
  now: number,
  source: ProblemSource = "spoken",
): SessionContext {
  const detected = detectProblemStart(question);
  return {
    activeProblem: {
      id: nextProblemId(),
      text: clipProblemText(question),
      kind: detected.kind,
      source,
      createdAt: now,
      lastUsedAt: now,
    },
    // A new problem INVALIDATES the previous approach summary: it described the
    // old one, and carrying it over would answer the new question with a plan
    // for a different problem. User notes survive, because they are pasted
    // material about the new problem too.
    approachSummary: null,
    // The THREAD survives: a new coding problem does not end the technical
    // discussion that was running alongside it. Part 18 requires the two layers
    // to coexist, and clearing one because the other changed would break exactly
    // the screen-plus-project scenario.
    conversationThread: ctx.conversationThread,
    userNotes: ctx.userNotes,
  };
}

/** Record that the context was used, so the TTL is "since last use". */
export function touchProblem(ctx: SessionContext, now: number): SessionContext {
  if (!ctx.activeProblem) return ctx;
  if (ctx.activeProblem.lastUsedAt === now) return ctx;
  return {
    ...ctx,
    activeProblem: { ...ctx.activeProblem, lastUsedAt: now },
  };
}