import { ipcMain } from "electron";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  DEBUG_CLIP_EXPORT_FILENAME,
  DEBUG_CLIP_ROOT_DIR,
  sessionFolderName,
} from "../src/lib/debugClipSave";

/**
 * Write a session's debug clips + comparison export to disk.
 *
 * ── Explicitly user-triggered ───────────────────────────────────────────────
 * This handler is only ever invoked by the "Save all debug clips" button. No
 * timer, no lifecycle hook, and no capture path writes anything: a session that
 * records debug audio still keeps it in memory only, exactly as before this
 * existed. Recording interview audio to disk is a deliberate act with legal
 * weight, so it must not happen as a side effect of anything.
 *
 * ── Why the main process ────────────────────────────────────────────────────
 * The renderer has no filesystem access. Writing from the renderer would mean
 * exposing an arbitrary-write bridge, which is a far larger hole than one
 * fixed-purpose, dev-only handler.
 *
 * ── Where ───────────────────────────────────────────────────────────────────
 * `debug-audio/<session-timestamp>/` relative to the app's working directory
 * (the project root in dev). That directory is gitignored, so interview audio
 * cannot be committed by accident. Nothing is uploaded anywhere.
 */

/** Per-file ceiling. 16 kHz mono 16-bit is ~32 KB/s, so this is minutes. */
const MAX_CLIP_BYTES = 60 * 1024 * 1024;
const MAX_TOTAL_BYTES = 200 * 1024 * 1024;

export interface DebugClipFileInput {
  /** Filename produced by `debugClipFileName`. */
  name: string;
  /** Raw WAV bytes. */
  data: Uint8Array;
}

export interface DebugClipSavePayload {
  /** Session timestamp; the main process generates it if absent. */
  session?: string;
  files: DebugClipFileInput[];
  /** The comparison export JSON, written beside the clips. */
  exportJson?: string;
}

export interface DebugClipSaveResult {
  ok: boolean;
  /** Absolute folder the files were written to. */
  dir?: string;
  written?: number;
  message?: string;
}

/**
 * Refuse anything that could escape the session folder.
 *
 * A filename is user-influenced in the sense that it comes from the renderer,
 * so `../../` and absolute paths must be rejected outright rather than
 * sanitised: there is no legitimate clip name that needs them.
 */
export function isSafeClipName(name: unknown): name is string {
  if (typeof name !== "string" || name.length === 0) return false;
  if (name.includes("/") || name.includes("\\")) return false;
  if (name.includes("..")) return false;
  if (name !== path.basename(name)) return false;
  return /^\d+_[\d.]+s\.wav$/.test(name);
}

export function registerDebugClipHandlers(options: {
  /** Injected for tests. Defaults to the app's working directory. */
  resolveRoot?: () => string;
} = {}): { getSessionDir: (session: string) => string } {
  const resolveRoot = options.resolveRoot ?? (() => process.cwd());
  const getSessionDir = (session: string): string =>
    path.join(resolveRoot(), DEBUG_CLIP_ROOT_DIR, session);

  ipcMain.handle(
    "asr:save-debug-clips",
    async (_event, payload: DebugClipSavePayload): Promise<DebugClipSaveResult> => {
      try {
        const files = Array.isArray(payload?.files) ? payload.files : [];
        if (files.length === 0) {
          return { ok: false, message: "no clips to save" };
        }

        const session = payload.session ?? sessionFolderName();
        // The session segment is generated by us, but it still reaches the
        // filesystem as a path component, so it is validated like any other.
        if (!/^\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}$/.test(session)) {
          return { ok: false, message: `unsafe session folder name: ${session}` };
        }

        let total = 0;
        for (const file of files) {
          if (!isSafeClipName(file?.name)) {
            return { ok: false, message: `unsafe clip filename: ${String(file?.name)}` };
          }
          if (!(file.data instanceof Uint8Array)) {
            return { ok: false, message: `clip ${file.name} has no bytes` };
          }
          if (file.data.byteLength > MAX_CLIP_BYTES) {
            return { ok: false, message: `clip ${file.name} is implausibly large` };
          }
          total += file.data.byteLength;
        }
        if (total > MAX_TOTAL_BYTES) {
          return { ok: false, message: "clip set is implausibly large" };
        }

        // Every WAV must really be a RIFF/WAVE file. A truncated or wrong file
        // would otherwise be imported later as though it were a valid capture.
        for (const file of files) {
          const head = Buffer.from(file.data.buffer, file.data.byteOffset, Math.min(12, file.data.byteLength));
          if (head.length < 12 || head.toString("ascii", 0, 4) !== "RIFF" || head.toString("ascii", 8, 12) !== "WAVE") {
            return { ok: false, message: `${file.name} is not a RIFF/WAVE file` };
          }
        }

        if (payload.exportJson !== undefined) {
          if (typeof payload.exportJson !== "string") {
            return { ok: false, message: "comparison export is not text" };
          }
          try {
            JSON.parse(payload.exportJson);
          } catch {
            return { ok: false, message: "comparison export is not valid JSON" };
          }
        }

        const dir = getSessionDir(session);
        await mkdir(dir, { recursive: true });

        for (const file of files) {
          await writeFile(path.join(dir, file.name), file.data);
        }
        if (payload.exportJson !== undefined) {
          await writeFile(
            path.join(dir, DEBUG_CLIP_EXPORT_FILENAME),
            payload.exportJson,
            "utf8",
          );
        }

        return { ok: true, dir, written: files.length };
      } catch (err) {
        return {
          ok: false,
          message: err instanceof Error ? err.message : String(err),
        };
      }
    },
  );

  return { getSessionDir };
}